import LinkedList from "./LinkedList.js";

const list = new LinkedList();
console.log("First, before adding anything");
console.log(`Size: ${list.size()}`);
console.log(`Head: ${list.head()}`);
console.log(`Tail: ${list.tail()}`);
console.log(`At position 0: ${list.at(0)}`);
console.log(`At position 1: ${list.at(1)}`);
console.log(`Attempt to pop: ${list.pop()}`);
console.log(`Does it contain dog? ${list.contains("dog")}`);
console.log(`Find dog: ${list.find("dog")}`);
console.log(list.toString());
list.append("dog");
list.append("cat");
list.append("parrot");
list.append("hamster");
list.append("snake");
list.append("turtle");
console.log("Then, after adding a bunch");
console.log(`Size: ${list.size()}`);
console.log(`Head: ${list.head()}`);
console.log(`Tail: ${list.tail()}`);
console.log(`At position 0: ${list.at(0)}`);
console.log(`At position 1: ${list.at(1)}`);
console.log(`At position 5: ${list.at(5)}`);
console.log(`At position 6: ${list.at(6)}`);
console.log(`Does it contain dog? ${list.contains("dog")}`);
console.log(`Does it contain hamster? ${list.contains("hamster")}`);
console.log(`Does it contain turtle? ${list.contains("turtle")}`);
console.log(`Find dog: ${list.find("dog")}`);
console.log(`Find hamster: ${list.find("hamster")}`);
console.log(`Find turtle: ${list.find("turtle")}`);
console.log(list.toString());
console.log(`Attempt to pop: ${list.pop()}`);
console.log(`Does it contain turtle? ${list.contains("turtle")}`);
console.log(`Find turtle: ${list.find("turtle")}`);
console.log(list.toString());
console.log("About to insert a snail at index 2");
list.insertAt("snail", 2);
console.log(list.toString());
console.log("About to remove the node at index 4");
list.removeAt(4);
console.log(list.toString());
console.log("About to remove the node at index 4 again, it's also the last one but it should work");
list.removeAt(4);
console.log(list.toString());
console.log("About to remove the node at index 0, first, should still work");
list.removeAt(0);
console.log(list.toString());